### recuperar todos los usuarios
GET http://localhost:8080/users

### recuperar usuario por ID
GET http://localhost:8080/users/6527d034ced742c79407e810

### actualizar un usuario por ID
PUT http://localhost:8080/users/652751aa0caf1c546794a893
Content-Type: application/json

{
    "first_name": "Johni",
    "last_name": "Doe",
    "email": "johndoe@example.com",
    "password": "secret",
    "role": "propietario"
}

### eliminar un usuario por ID
DELETE http://localhost:8080/users/652751aa0caf1c546794a893

### crear un usuario
POST http://localhost:8080/users
Content-Type: application/json 

{
    "first_name": "Marcos",
    "last_name": "Martin",
    "email": "johnMarcos@example.com",
    "password": "secret",
    "role": "propietario"
}