name: E2E on Chrome
on:
  push:
    branches:
      - test

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          build: npm run build
          start: npm start